version = 1
SPDX-PackageName = "libdkapture"
SPDX-PackageSupplier = "UnionTech Software Technology Co., Ltd"
SPDX-PackageDownloadLocation = "https://github.com/DKapture/libdkapture"

[[annotations]]
path = [
	"README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd"
SPDX-License-Identifier = "LGPL-2.1-only"

[[annotations]]
path = [
	".gitignore"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"